name = "NameResolution"
uuid = "71a1bf82-56d0-4bbc-8a3c-48b961074391"
authors = ["thautwarm"]
version = "0.1.4"

[deps]
PrettyPrint = "8162dcfd-2161-5ef2-ae6c-7681170c5f98"

[compat]
PrettyPrint = "^0.2.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
